### ISSUE TITLE
Peer-peer code review

### ISSUE THREAD

**Issue by Mukumbuta** [michael-duke/Awesome-Books#4]
Hello @michael-duke and @aceDavon 
Great job on this project 👍🏾. However, you may consider the following optional adjustments.
- Consider adding validations for empty submissions.
- Display a notification when the user successfully adds a book, and
- Make sure the date displays responsively on the mobile version.

**Comment by michael-duke** [comment]
Thank you @Mukumbuta and @kessio for your feedback, I have updated the changes as requested and made the fixes we discussed [Link](https://michael-duke.github.io/Awesome-Books/) here
